version: '3.8'

services:
  streamlit:
    build: .
    container_name: st_docx
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: docx_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data

volumes:
  sqlite_data: