version: '3.8'

services:
  streamlit_app:
    build: ./frontend
    container_name: st_docx
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - docx_network
    env_file:
      - .env

  backend:
    build: ./backend
    container_name: docx_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    networks:
      - docx_network
    env_file:
      - .env

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - docx_network
      
networks:
  docx_network:
    driver: bridge

volumes:
  sqlite_data: